[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "remove-json-keys"
version = "0.0.13"
description = "Remove key/value pairs from json_dir/**/*.json."
authors = [{name = "Adam Lui", email = "adam@kudoai.com"}]
license = "MIT"
license-files = ["LICENSE.md"]
keywords = ["json", "data"]

[project.scripts]
remove-json-keys = "remove_json_keys.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["package_data.json", "*.md"]
