[project]
name = "remove-json-keys"
version = "0.0.11"
description = "Remove key/value pairs from json_dir/**/*.json."
authors = [{name = "Adam Lui", email = "adam@kudoai.com"}]

[project.scripts]
remove-json-keys = "remove_json_keys.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["package_data.json", "*.md"]
