[project]
name = "remove-json-keys"
version = "0.0.6"
description = "Remove key/value pairs from json_dir/**/*.json. Type remove-json-keys --help to view options."
authors = [{name = "Adam Lui", email = "adam@kudoai.com"}]

[project.scripts]
remove-json-keys = "remove_json_keys.__main__:main"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"*" = ["package-data.json", "*.md"]
