[project]
name = "remove-json-keys"
version = "0.0.12"
description = "Remove key/value pairs from json_dir/**/*.json."
authors = [{name = "Adam Lui", email = "adam@kudoai.com"}]
license = "MIT"
license-files = ["LICENSE.md"]

[project.scripts]
remove-json-keys = "remove_json_keys.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["package_data.json", "*.md"]
